### PR TITLE
[!!!] Rename `*Table` types to `*Map`

### PR DESCRIPTION
**Pull request by haxscramper**
Reasoning described in #31

There is absolutely no consistency in any other language in terms of naming ordered/unordered associative containers (some call trees maps, some hashes, some use both names, sometimes neither of the names are used), so it was mostly just arbitrary decision to name it `Map`. Adding "BTree" or "Binary" prefix is probably not really useful anyway, since it makes type ~2 longer to type without bringing any benefit over `Map`.

### CODE REVIEW

**Comment by juancarlospaco** [comment]
Needs changelog.

**Comment by planetis-m** [comment]
Anyone else has an opinion if this rename is necessary?

**Comment by liquid600pgm** [comment]
I'd prefer if the btreetables were renamed to `BinaryTable` or `TreeTable`, `Map` is not descriptive enough in my opinion.

**Comment by haxscramper** [comment]
I don't really care about *exact naming* - `BTable`, or `TreeTable` or `Map` or `SortedTable` or whatever - just not the same as `std/tables.Table`.

**Comment by Araq** [comment]
Rejected for multiple reasons:

- We don't rename things in fusion, this is stable software you can use.
- We made it compatible (names included) with std/tables as a decision choice so that code can easily simply change the import to get the other table implementation.
- You can easily import both modules and use ``A.Table`` vs ``B.Table`` notations.

**Pull request closed without merging**
