### PR TITLE
Fix #74

### LINKED ISSUE #74: deprecate or remove fusion/[jsformdata,jsheaders] because of the new [std/jsformdata,jsheaders]
/cc @juancarlospaco 
* deprecate or remove fusion/[jsformdata,jsheaders] because of the new [std/jsformdata,jsheaders] (since https://github.com/nim-lang/Nim/pull/12531)

* what about fusion/js/jsxmlhttprequest.nim? is there equivalent in stdlib?

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Fix #74 
- Unrelated CI fail

```
Run alaviss/setup-nim@0.1.1
Error: Could not find any release named 'latest-version-1-2'. The provided branch (version-1-2) might not be tracked by nightlies, or is being updated.
Error: Process completed with exit code 1.
```

### CODE REVIEW

**Review by timotheecour — APPROVED** [review]
LGTM, but let's confirm with others to make sure ok to remove (recent additions)

**Comment by juancarlospaco** [comment]
@timotheecour 
So... any news?, can we Merge ?, it literally just deletes a file.

**Comment by juancarlospaco** [comment]
Ping @xflywind or someone...

**Comment by timotheecour** [comment]
merged, no point in leaving PR's rot forever.

**Comment by juancarlospaco** [comment]
Thanks very much.

**Pull request merged**
