### PR TITLE
ci: see if setup-nim is faster than choosenim

### PR DESCRIPTION
**Pull request by alaviss**

### CODE REVIEW

**Review by timotheecour — APPROVED** [review]

**Comment by timotheecour** [comment]
I like that it:
* avoids this problem https://github.com/jiro4989/setup-nim-action/issues/38 with jiro4989/setup-nim-action
* avoids the slow osx installation times noted in https://github.com/nim-lang/fusion/issues/69#issuecomment-755010291

are there any downsides?

**Comment by alaviss** [comment]
None as far as I can tell. @disruptek has been using this on all of his projects and so far it seems fine.

**Comment by jiro4989** [comment]
> None as far as I can tell. @disruptek has been using this on all of his projects and so far it seems fine.

LGTM 👍

**Comment by juancarlospaco** [comment]
```
Run alaviss/setup-nim@0.1.1
Error: Could not find any release named 'latest-version-1-2'. The provided branch (version-1-2) might not be tracked by nightlies, or is being updated.
Error: Process completed with exit code 1.
```

**Pull request merged**
